apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: recipes-service
  name: recipes-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: recipes-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: recipes-service
    spec:
      containers:
        - env:
            - name: INGREDIENT_SERVICE_BASEURL
              value: ingredients-service:8080
            - name: MYSQL_DB_HOST
              value: mysql-recipes
            - name: MYSQL_DB_PASSWORD
              value: abc123
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_USERNAME
              value: root
            - name: UTENSIL_SERVICE_BASEURL
              value: utensils-service:8082
          image: maartenhens/recipes-service
          name: recipes-service
          ports:
            - containerPort: 8081
          resources: {}
      restartPolicy: Always
status: {}
