apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: utensils-service
  name: utensils-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: utensils-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/backend: "true"
        io.kompose.service: utensils-service
    spec:
      containers:
        - env:
            - name: MYSQL_DB_HOST
              value: mysql-utensils
            - name: MYSQL_DB_PASSWORD
              value: abc123
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_USERNAME
              value: root
          image: maartenhens/utensils-service
          name: utensils-service
          ports:
            - containerPort: 8082
          resources: {}
      restartPolicy: Always
status: {}
